### ISSUE TITLE
How plug it into phoenix project and the configure it ?

### ISSUE THREAD

**Issue by developerworks** [mneudert/plug_accesslog#11]
I create a `blog` project with the command: `mix phoenix.new blog --database mysql` and the default `web/router.ex` code is:

``` elixir
defmodule Blog.Router do
  use Blog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Blog do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", Blog do
  #   pipe_through :api
  # end
end
```

Thank you.

**Comment by mneudert** [comment]
After you have added the application `:plug_accesslog` to the list of started applications in your `mix.exs` the following snippet copied to your `:browser` pipeline block should get you up and running:

``` elixir
plug Plug.AccessLog, file: "/tmp/blog_access.log"
```

The logs should then be written to the file "/tmp/blog_access.log". Of course this file can be changed to your liking, the README.md should contain all information about the configuration of the logs.

If you are actively using the pipelines you should then consider also adding the logging to your other pipelines. Using the same file with multiple endpoints should pose no problem and more or less just aggregate all the logs in one place.

**Comment by developerworks** [comment]
`mix.exs`:

``` elixir
defmodule Blog.Mixfile do
  use Mix.Project

  def project do
    [app: :blog,
     version: "0.0.1",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type `mix help compile.app` for more information
  def application do
    [mod: {Blog, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger,
                    :phoenix_ecto, :mariaex, :plug_accesslog]]
  end

  # Specifies which paths to compile per environment
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies
  #
  # Type `mix help deps` for examples and options
  defp deps do
    [{:phoenix, "~> 1.0.2"},
     {:phoenix_ecto, "~> 1.1"},
     {:mariaex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"},
     {:plug_ribbon, "~> 0.2.0"},
     {:plug_accesslog, "~> 0.9"}]
  end
end

```

The full code of `web/router.ex`

``` elixir

defmodule Blog.Router do
  use Blog.Web, :router

  #defmodule LogFilter do
  #  def dontlog?(conn), do: "/favicon.ico" == full_path(conn)
  #end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plug.Ribbon, [:dev, :staging, :test]
    plug Plug.AccessLog,
      format: :clf,
      file: "/tmp/blog_access.log"
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Plug.AccessLog, format: :clf, file: "/tmp/blog_access.log"
  end

  scope "/", Blog do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    #get "/", PostController, :index
    resources "/posts", PostController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Blog do
  #   pipe_through :api
  # end
end
```

Throws an exception:

```
[info] Running Blog.Endpoint with Cowboy on http://localhost:4000
[info] GET /
[debug] Processing by Blog.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[error] #PID<0.363.0> running Blog.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
        lib/tzdata/release_reader.ex:41: Tzdata.ReleaseReader.current_release_from_table/0
        lib/tzdata/release_reader.ex:13: Tzdata.ReleaseReader.simple_lookup/1
        lib/tzdata/release_reader.ex:7: Tzdata.ReleaseReader.zone_and_link_list/0
        lib/tzdata.ex:61: Tzdata.zone_exists?/1
        lib/timezone/timezone.ex:113: Timex.Timezone.get/2
        lib/date/date.ex:307: Timex.Date.from/2
        (plug_accesslog) lib/plug/accesslog/default_formatter/request_time.ex:19: Plug.AccessLog.DefaultFormatter.RequestTime.request_time/1
        (plug_accesslog) lib/plug/accesslog/default_formatter/request_time.ex:12: Plug.AccessLog.DefaultFormatter.RequestTime.append/2
        (plug_accesslog) lib/plug/accesslog/default_formatter.ex:130: Plug.AccessLog.DefaultFormatter.log/3
        (plug_accesslog) lib/plug/accesslog/formatter.ex:42: Plug.AccessLog.Formatter.format/3
        (plug_accesslog) lib/plug/accesslog.ex:51: Plug.AccessLog.log/2
        (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
        (plug) lib/plug/conn.ex:871: Plug.Conn.run_before_send/2
        (plug) lib/plug/conn.ex:330: Plug.Conn.send_resp/1
        (plug) lib/plug/debugger.ex:116: Plug.Debugger.__catch__/5
        (blog) lib/phoenix/endpoint/render_errors.ex:34: Blog.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
29 Sep 02:52:39 - info: compiled 5 files into 2 files, copied 3 in 1330ms
```

**Comment by mneudert** [comment]
Ah, I have seen that error :D

The problem is the `:tzdata` module (dependency of `:timex`) in the version you are loading. Somewhere between the one stated in the `mix.lock` file ("0.1.7") and today there have been various changes. Please try adding `:tzdata` to the list of started applications.

If that solves it I will try to send out a patch release of plug_accesslog to prevent these misleading errors.

**Comment by developerworks** [comment]
It works.
very very thanks.
